"""KBS Beauty Saloon default service catalog (seeded to Mongo on startup)."""

SERVICES = [
    # SPECIAL COMBOS
    {"name": "Korean Combo Package", "price": 10000, "category": "Special Combos", "subcategory": "Combos", "gender": "unisex", "description": "Korean Spa + Korean Pedicure + Korean Facial"},

    # MEN — Hair Cuts & Styling
    {"name": "Beard Trim", "price": 100, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Boy Hair Cut", "price": 150, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Hair Cut", "price": 200, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Change of Style", "price": 350, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Shave with Foam", "price": 100, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Hair Style + Shampoo", "price": 150, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Head Shave", "price": 200, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Shampoo", "price": 100, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Shampoo & Conditioner", "price": 150, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},
    {"name": "Shampoo / Conditioner / Blowdry", "price": 180, "category": "Men's Services", "subcategory": "Hair Cuts & Styling", "gender": "men"},

    # MEN — Hair Coloring
    {"name": "Beard Dye", "price": 300, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},
    {"name": "Hair Dye Application", "price": 300, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},
    {"name": "Hair Dye - Majirel", "price": 1000, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},
    {"name": "Hair Dye - Inoa", "price": 1000, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},
    {"name": "Side Locks Dye", "price": 150, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},
    {"name": "Mustache Dye", "price": 100, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},
    {"name": "Fashion Colour - Majirel", "price": 1200, "priceMax": 1500, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},
    {"name": "Fashion Colour - Inoa", "price": 1200, "priceMax": 1500, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},
    {"name": "Hair Streaking", "price": 800, "priceMax": 1500, "category": "Men's Services", "subcategory": "Hair Coloring", "gender": "men"},

    # MEN — Hair Treatments
    {"name": "Hair Protein Treatment", "price": 2000, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Hair Spa Treatment", "price": 800, "priceMax": 1200, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Colour Save Treatment", "price": 500, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Deep Conditioning", "price": 600, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Hair Fall Treatment", "price": 1500, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Dandruff Treatment", "price": 1500, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Straightening", "price": 4000, "priceMax": 6000, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Pumping", "price": 5000, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Botox Medium", "price": 3000, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},
    {"name": "Nanoplus", "price": 3000, "category": "Men's Services", "subcategory": "Hair Treatments", "gender": "men"},

    # WOMEN — Hair Cuts
    {"name": "Baby Haircut", "price": 200, "category": "Women's Services", "subcategory": "Hair Cuts", "gender": "women"},
    {"name": "Baby Haircut Styling", "price": 350, "category": "Women's Services", "subcategory": "Hair Cuts", "gender": "women"},
    {"name": "Basic Haircut", "price": 400, "category": "Women's Services", "subcategory": "Hair Cuts", "gender": "women"},
    {"name": "Advanced Haircut", "price": 1000, "category": "Women's Services", "subcategory": "Hair Cuts", "gender": "women"},
    {"name": "Haircut Fringe", "price": 150, "category": "Women's Services", "subcategory": "Hair Cuts", "gender": "women"},

    # WOMEN — Wash & Styling
    {"name": "Shampoo with Conditioner", "price": 500, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Shampoo with Conditioner (Long)", "price": 800, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Shampoo Conditioner with Power Mask", "price": 700, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Straight Hair Blow Setting", "price": 500, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Ultimate Blow Setting", "price": 650, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Creative Hair Styles", "price": 900, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Creative Updos", "price": 1200, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Ironing - Short", "price": 1500, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Ironing - Mid", "price": 2000, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Ironing - Long", "price": 2500, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Tongs - Short", "price": 1500, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},
    {"name": "Tongs - Mid", "price": 2000, "category": "Women's Services", "subcategory": "Hair Wash & Styling", "gender": "women"},

    # WOMEN — Care, Spa & Treatments
    {"name": "Hair Spa - Short", "price": 1500, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Hair Spa - Medium", "price": 2000, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Hair Spa - Long", "price": 2500, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Organ Oil Spa", "price": 2000, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Methinic Oil Treatment", "price": 1200, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Nashi Spa", "price": 2500, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Moroccan Spa", "price": 2500, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Protein Treatment", "price": 1500, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Split End Removal", "price": 1000, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Deep Conditioning (Women)", "price": 1500, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Straightening / Botox", "price": 10000, "priceMax": 15000, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},
    {"name": "Keratin / Nanoplastia", "price": 10000, "priceMax": 20000, "category": "Women's Services", "subcategory": "Care, Spa & Treatments", "gender": "women"},

    # WOMEN — Hair Colour
    {"name": "Root Touch Up Majirel", "price": 1200, "category": "Women's Services", "subcategory": "Hair Colour", "gender": "women"},
    {"name": "Root Touch Up Inoa", "price": 1500, "category": "Women's Services", "subcategory": "Hair Colour", "gender": "women"},
    {"name": "Global Colour", "price": 2500, "category": "Women's Services", "subcategory": "Hair Colour", "gender": "women"},
    {"name": "Global Fashion Colour", "price": 3500, "category": "Women's Services", "subcategory": "Hair Colour", "gender": "women"},
    {"name": "Full Streaking", "price": 3500, "category": "Women's Services", "subcategory": "Hair Colour", "gender": "women"},
    {"name": "Single Streaking", "price": 400, "category": "Women's Services", "subcategory": "Hair Colour", "gender": "women"},

    # WOMEN — Threading
    {"name": "Threading - Eyebrows", "price": 50, "category": "Women's Services", "subcategory": "Threading", "gender": "women"},
    {"name": "Threading - Upper Lip", "price": 30, "category": "Women's Services", "subcategory": "Threading", "gender": "women"},
    {"name": "Threading - Forehead", "price": 30, "category": "Women's Services", "subcategory": "Threading", "gender": "women"},
    {"name": "Threading - Chin", "price": 30, "category": "Women's Services", "subcategory": "Threading", "gender": "women"},
    {"name": "Threading - Side Locks", "price": 60, "category": "Women's Services", "subcategory": "Threading", "gender": "women"},
    {"name": "Threading - Full Face", "price": 200, "category": "Women's Services", "subcategory": "Threading", "gender": "women"},

    # WOMEN — Piercing
    {"name": "Ear Piercing", "price": 500, "category": "Women's Services", "subcategory": "Piercing", "gender": "women"},
    {"name": "Nose Piercing", "price": 500, "category": "Women's Services", "subcategory": "Piercing", "gender": "women"},

    # Pedicure / Manicure
    {"name": "Basic Pedicure", "price": 500, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},
    {"name": "Basic Manicure", "price": 500, "category": "Pedicure & Manicure", "subcategory": "Manicure", "gender": "unisex"},
    {"name": "Raaga Pedicure", "price": 1000, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},
    {"name": "Raaga Manicure", "price": 1000, "category": "Pedicure & Manicure", "subcategory": "Manicure", "gender": "unisex"},
    {"name": "O3 Pedicure", "price": 1500, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},
    {"name": "O3 Manicure", "price": 1500, "category": "Pedicure & Manicure", "subcategory": "Manicure", "gender": "unisex"},
    {"name": "Spa Pedicure", "price": 1000, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},
    {"name": "Spa Manicure", "price": 1000, "category": "Pedicure & Manicure", "subcategory": "Manicure", "gender": "unisex"},
    {"name": "Chocolate Pedicure", "price": 900, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},
    {"name": "Chocolate Manicure", "price": 900, "category": "Pedicure & Manicure", "subcategory": "Manicure", "gender": "unisex"},
    {"name": "Candle Pedicure", "price": 1000, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},
    {"name": "Candle Manicure", "price": 1000, "category": "Pedicure & Manicure", "subcategory": "Manicure", "gender": "unisex"},
    {"name": "Crystal Pedicure", "price": 1500, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},
    {"name": "Crystal Manicure", "price": 1500, "category": "Pedicure & Manicure", "subcategory": "Manicure", "gender": "unisex"},
    {"name": "O3+ Pedicure", "price": 1200, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},
    {"name": "Heel Peel Pedicure", "price": 2000, "category": "Pedicure & Manicure", "subcategory": "Pedicure", "gender": "unisex"},

    # Massages, Packs & Body Care
    {"name": "Head Massage - Coconut Oil", "price": 700, "category": "Massages & Body Care", "subcategory": "Head Massages", "gender": "unisex"},
    {"name": "Head Massage - Almond Oil", "price": 800, "category": "Massages & Body Care", "subcategory": "Head Massages", "gender": "unisex"},
    {"name": "Head Massage - Mint Oil", "price": 600, "category": "Massages & Body Care", "subcategory": "Head Massages", "gender": "unisex"},
    {"name": "Head Massage - Dandruff", "price": 645, "category": "Massages & Body Care", "subcategory": "Head Massages", "gender": "unisex"},
    {"name": "Head Massage - Olive Oil", "price": 800, "category": "Massages & Body Care", "subcategory": "Head Massages", "gender": "unisex"},
    {"name": "Head Massage Pack", "price": 350, "category": "Massages & Body Care", "subcategory": "Head Massages", "gender": "unisex"},
    {"name": "Foot Reflexology", "price": 1500, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},
    {"name": "Leg Massage", "price": 500, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},
    {"name": "Aroma Oil Body Massage", "price": 1800, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},
    {"name": "Olive Oil Body Massage", "price": 1800, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},
    {"name": "Almond Oil Body Massage", "price": 1500, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},
    {"name": "Mint Oil Body Massage", "price": 2500, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},
    {"name": "Body Massage with Scrub", "price": 3000, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},
    {"name": "Massage with Scrub & Cream", "price": 3500, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},
    {"name": "Body Polishing", "price": 4000, "category": "Massages & Body Care", "subcategory": "Body Massages & Care", "gender": "unisex"},

    # Cleanups, Facials & D-Tan
    {"name": "Bio Whitening Mask", "price": 800, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Skin Lightening Mask", "price": 600, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Thermo Mask", "price": 500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Collagen Mask", "price": 950, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "De-Pigmentation Mask", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Sebum Controlling Mask", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Ozone / O3 Peel Off Mask", "price": 1000, "priceMax": 1500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Regular Cleanup", "price": 400, "priceMax": 500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Fruit Cleanup", "price": 600, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Gold Cleanup Natures", "price": 800, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Gold Cleanup Shehnaz", "price": 1200, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Pearl Cleanup", "price": 650, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Skin Lightening Cleanup", "price": 900, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "Bio Whitening Cleanup", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "O3 Seaweed Cleanup", "price": 2000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},
    {"name": "O3 Gold Cleanup", "price": 2250, "category": "Cleanups, Facials & D-Tan", "subcategory": "Masks & Cleanups", "gender": "unisex"},

    {"name": "Regular Facial", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Herbal Facial", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Fruit Facial", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Papaya Facial", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Banana Facial", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Mixed Facial", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Sensicalm Facial", "price": 1300, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Anti-Aging Facial", "price": 1500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Pearl Facial", "price": 1500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Raga Facial", "price": 1500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Chocolate Facial", "price": 1500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Diamond Facial", "price": 1500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Whitening Facial", "price": 1500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Lotus Facial", "price": 2000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},
    {"name": "Gold Natures Facial", "price": 2000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Basic Facials", "gender": "unisex"},

    {"name": "Bio Whitening (Advanced)", "price": 2000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},
    {"name": "Pollution Define", "price": 2250, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},
    {"name": "Gold Shehnaz Facial", "price": 2500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},
    {"name": "Diamond Shehnaz Facial", "price": 2700, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},
    {"name": "O3 Intensive Hydrating", "price": 2700, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},
    {"name": "O3 Skin Lightening", "price": 3000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},
    {"name": "Lotus Advanced", "price": 3000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},
    {"name": "O3 Seaweed Facial", "price": 3700, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},
    {"name": "O3 Gold / Main O3 Facial", "price": 4000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Advanced Facials", "gender": "unisex"},

    {"name": "D-Tan Face", "price": 350, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Face & Neck", "price": 500, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Face Neck Blouse Line", "price": 700, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Upper Back", "price": 430, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Under Arms", "price": 150, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Full Arms", "price": 695, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Full Legs", "price": 850, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Feet", "price": 200, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Full Back", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "D-Tan Full Body", "price": 3000, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},
    {"name": "O3 D-Tan", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "D-Tan", "gender": "unisex"},

    {"name": "Waxing Half Arms", "price": 200, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Half Arms D-Tan", "price": 300, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Full Arms", "price": 350, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Full Arms D-Tan", "price": 500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Half Legs", "price": 350, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Half Legs D-Tan", "price": 500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Full Legs", "price": 1000, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Upper Back", "price": 500, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Under Arms", "price": 250, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Upper Lip", "price": 60, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Chin", "price": 60, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Side Locks", "price": 125, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    {"name": "Waxing Face", "price": 200, "category": "Cleanups, Facials & D-Tan", "subcategory": "Waxing", "gender": "women"},
    # BRIDAL & GROOM (exclusively bridal section)
    {"name": "Economy Pre-Bridal Package", "price": 8383, "category": "Bridal & Groom", "subcategory": "Pre-Bridal Packages", "gender": "women", "description": "Cleanse, glow & pre-wedding hair rituals"},
    {"name": "Executive Pre-Bridal Package", "price": 15090, "category": "Bridal & Groom", "subcategory": "Pre-Bridal Packages", "gender": "women", "description": "Advanced facials, spa, body polish & mani-pedi"},
    {"name": "Economy Pre-Groom Package", "price": 5216, "category": "Bridal & Groom", "subcategory": "Pre-Groom Packages", "gender": "men", "description": "Grooming essentials for the big day"},
    {"name": "Executive Pre-Groom Package", "price": 11385, "category": "Bridal & Groom", "subcategory": "Pre-Groom Packages", "gender": "men", "description": "Full spa, facial & styling package"},
    {"name": "Bridal Makeup - Classic", "price": 3000, "category": "Bridal & Groom", "subcategory": "Bridal Makeup", "gender": "women", "description": "Signature classic bridal look"},
    {"name": "Bridal Makeup - Signature", "price": 5000, "category": "Bridal & Groom", "subcategory": "Bridal Makeup", "gender": "women", "description": "Editorial glam with HD finish"},
    {"name": "Bridal Makeup - Couture", "price": 8000, "category": "Bridal & Groom", "subcategory": "Bridal Makeup", "gender": "women", "description": "Airbrush + hair + drapery"},
    {"name": "Mehendi - Simple Design", "price": 500, "category": "Bridal & Groom", "subcategory": "Mehendi Services", "gender": "women", "description": "Elegant motifs for engagement"},
    {"name": "Mehendi - Full Hands & Feet", "price": 2000, "category": "Bridal & Groom", "subcategory": "Mehendi Services", "gender": "women", "description": "Traditional bridal mehendi"},
    {"name": "Mehendi - Royal Bridal Set", "price": 4000, "category": "Bridal & Groom", "subcategory": "Mehendi Services", "gender": "women", "description": "Full bridal — hands, arms, legs, feet"},
]

STYLISTS = [
    {"name": "Any Available", "specialty": "First available beautician", "badge": "", "top_rated": False},
    {"name": "Neeraj", "specialty": "Master Stylist", "badge": "Master Stylist · 4.9 ★", "top_rated": True},
    {"name": "Bujji", "specialty": "Senior Colorist", "badge": "Senior Colorist · 4.9 ★", "top_rated": True},
    {"name": "Naidu", "specialty": "Barber & Hair Specialist", "badge": "Barber & Hair Specialist", "top_rated": False},
    {"name": "Aruna", "specialty": "Skin & Spa Specialist", "badge": "Skin & Spa Specialist", "top_rated": False},
    {"name": "Akhil", "specialty": "Grooming & Hair Stylist", "badge": "Grooming & Hair Stylist", "top_rated": False},
]
